# Basic CI workflow for GitHub Actions

name: CI

# Define when the workflow should run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Define jobs for the workflow
jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a simple script
        run: echo "Hello, GitHub Actions!"

      - name: Run multi-line commands
        run: |
          echo "Executing multiple commands"
          echo "You can add build, test, or deploy steps here"

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./  # Adjust this based on your build output
